name: CI

on:
  - workflow_dispatch

env:
  COLUMNS: 150
  UV_FROZEN: true
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:

  core-build:
    name: core / Build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.interpreter || 'all' }}${{ matrix.os == 'linux' && format(' - {0}', matrix.manylinux == 'auto' && 'manylinux' || matrix.manylinux) || '' }})
    # only run on push to main, if a full build was requested or on release:
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        target: [undefined]
        include:
          # windows;
          # x86_64 pypy builds are not PGO optimized
          # i686 not supported by pypy
          # windows 11 arm supports 3.11 and up, not PGO optimized for now
          - os: windows
            target: x86_64
            interpreter: 3.12

        exclude:
          # was just a dummy variable to set a default value for target
          - target: undefined

    runs-on: ${{ matrix.runs-on || format('{0}-latest', (matrix.os == 'linux' && 'ubuntu') || matrix.os) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
          architecture: ${{ matrix.python-architecture || 'x64' }}

      - run: pip install -U twine 'ruff==0.5.0' typing_extensions

      - name: Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad # v1.50.1
        with:
          working-directory: pydantic-core
          target: x86_64-pc-windows-msvc
          manylinux: ${{ matrix.manylinux }}
          args: --release --release -Z build-std --target x86_64-win7-windows-msvc --out dist --interpreter ${{ matrix.interpreter || '3.9 3.10 3.11 3.12 3.13 3.14 3.14t pypy3.11' }}
          rust-toolchain: nightly
          rustup-components: rust-src
          docker-options: -e CI

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} dist/
        working-directory: pydantic-core

      - run: twine check --strict dist/*
        working-directory: pydantic-core

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: pydantic_core_pypi_files_${{ matrix.os }}_${{ matrix.target }}_${{ matrix.interpreter || 'all' }}_${{ matrix.manylinux }}
          path: pydantic-core/dist
